id: IBB8C8878
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:29:52.181283
last_modified: 2023-01-04 11:29:52.181294
source_metadata:
  collections:
  - Apang Tertön Series
  - Works of Tibetan Masters
bases:
  18B3:
    title: Daily Practice of Vajrakīla
    base_file: 18B3.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
